networks:
  cloudflared_proxy:
    external: true

services:

  backend:
    container_name: datafilter-backend
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile-backend
    image: datafilter-backend:latest
    # ports:
    #   - "8000:8000"
    # volumes:
    #   - ./data_output:/app/datafilter/data/output
    networks:
      - default
      - cloudflared_proxy

  frontend:
    container_name: datafilter-frontend
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    image: datafilter-frontend:latest
    environment:
      - VITE_API_URL=https://api.ptitgourmand.uk/datafilter
    # ports:
    #   - "5173:5173"
    networks:
      - default
      - cloudflared_proxy
